title: DayZ Manual
email: sepensi@gmail.com
description: >-
  My notes and instructions on how to set up, run maintain and mod a DayZ server.
  Included are also notes and instructions on how to mod DayZ.
baseurl: ""
url: ""
twitter_username: sepensai
github_username:  Vincibean

remote_theme: sighingnow/jekyll-gitbook